---
title: "rn4-behavior-analyses"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include = 'false'}
library(Rmisc)
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(ggrain)
library(ggsignif)
library(wesanderson)
library(gridExtra)

library(afex)
```

## Open datafile

Open the original csv files and combine for every session and participant
```{r open data}
path = '/Users/rosenasrawi/Documents/VU PhD/Projects/rn4 - Vis-mot four items/Data/Lab data/logfiles/'

subjectIDs = 1:25
sessions = c('a', 'b')

data = c() # Empty to start

for (sID in subjectIDs){

  for (ses in sessions){
    filename = paste('rn4_s', as.character(sID), ses, '.csv', sep = "")
    sub_data = read.csv(paste(path, filename, sep = ""))
    
    numtrials = dim(sub_data)[1] # number of rows in new file
    sub_data$subjectID = rep(sID, numtrials)
    
    data = rbind(data, sub_data) # Add every session to 1 file
  }
  
}

head(data)

```

## Clean data

Clean the data by decision times

```{r hist raw data}
histogram(data$responseTime)
```

```{r clean data}

# Mark trials with extreme slow/fast DT

slow_trials_all = c()

for (sub in unique(data$subjectID)){
  
  mean_sub = mean(data$responseTime[which(data$subjectID == sub)])
  sd_sub = sd(data$responseTime[which(data$subjectID == sub)]) * 2.5
  
  cutoff_slow = mean_sub + sd_sub
  
  slow_trials_sub = which(data$subjectID == sub & data$responseTime > cutoff_slow)
  
  if (length(slow_trials_sub) >= 1){
    slow_trials_all = c(slow_trials_all, slow_trials_sub)
  }
  
}

slow_trials_all = as.numeric(slow_trials_all)

data$responseTimeClean = data$responseTime
data$responseTimeClean[slow_trials_all] = NaN
data$responseTimeClean[which(data$responseTime >= 5)] = NaN
data$responseTimeClean[which(data$responseTime <= 0.1)] = NaN

data$goodBadTrials = T
data$goodBadTrials[slow_trials_all] = F
data$goodBadTrials[which(data$responseTime >= 5)] = F
data$goodBadTrials[which(data$responseTime <= 0.1)] = F

# Corrected report ori for dial change

data <- data %>% 
  mutate(reportOriCorr = if_else(dialType == "R" & reportOri > 90, as.integer(reportOri - 180), reportOri)) %>% 
  mutate(wrongDir = (targetOri * reportOriCorr) < 0)
  

# Check per condition
data %>% group_by(dialType, loadType) %>% summarise(mean(wrongDir))

```
```{r as factors}

data$subjectID = as.factor(data$subjectID)

data$loadType = as.factor(data$loadType)
levels(data$loadType) = c("Two", "Four")

data$dialType = as.factor(data$dialType)
levels(data$dialType) = c("Right", "Up")
```


```{r performance split}

med.RT1.subj = tapply(data$responseTimeClean, list(data$subjectID, data$loadType, data$dialType), FUN = median, na.rm=TRUE)
fastSlow = data$responseTimeClean

med.err.subj = tapply(data$difference, list(data$subjectID, data$loadType, data$dialType), FUN = median, na.rm=TRUE)
precImprec = data$difference

for (sub in 1:length(levels(data$subjectID))){
  for (load in 1:length(levels(data$loadType))){
    for (dial in 1:length(levels(data$dialType))){
      
      this.sub = levels(data$subjectID)[sub]
      this.load = levels(data$loadType)[load]
      this.dial = levels(data$dialType)[dial]
      
      this.med.RT = med.RT1.subj[sub,load,dial]
      this.med.err = med.err.subj[sub,load,dial]
      this.condition = data$subjectID == this.sub & data$loadType == this.load & data$dialType == this.dial

      fastSlow[this.condition & data$responseTimeClean > this.med.RT] = 'slow'
      fastSlow[this.condition & data$responseTimeClean < this.med.RT] = 'fast'
      fastSlow[this.condition & data$responseTimeClean == this.med.RT] = NaN
      
      precImprec[this.condition & data$difference < this.med.err] = 'prec'
      precImprec[this.condition & data$difference > this.med.err] = 'imprec'
      precImprec[this.condition & data$difference == this.med.err] = NaN
      
    }
  } 
}

data$fastSlow = fastSlow
data$precImprec = precImprec

```


```{r save combined logfile}

write.csv(data, file = paste(path,'combined_logfile.csv', sep=''), row.names = F)

```


## Summarise the data

```{r behavior, load x dial}

data$responseTimeClean = data$responseTimeClean*1000

# RT

summary.rt.subj.load.dial = aggregate(data = data, 
                                      responseTimeClean ~ subjectID + dialType + loadType, 
                                      mean)

summary.rt.load.dial = summarySEwithin(data = summary.rt.subj.load.dial,
                                       measurevar = "responseTimeClean",
                                       withinvars = c("dialType", "loadType"),
                                       idvar = "subjectID")

summary.rt.subj.load = aggregate(data = data, 
                                 responseTimeClean ~ subjectID + loadType, 
                                 mean)

summary.rt.load = summarySEwithin(data = summary.rt.subj.load,
                                  measurevar = "responseTimeClean",
                                  withinvars = "loadType",
                                  idvar = "subjectID")

# Err

summary.err.subj.load.dial = aggregate(data = data, 
                                       difference ~ subjectID + dialType + loadType, 
                                       mean)

summary.err.load.dial = summarySEwithin(data = summary.err.subj.load.dial,
                                        measurevar = "difference",
                                        withinvars = c("dialType", "loadType"),
                                        idvar = "subjectID")

summary.err.subj.load = aggregate(data = data, 
                                  difference ~ subjectID + loadType, 
                                  mean)

summary.err.load = summarySEwithin(data = summary.err.subj.load,
                                   measurevar = "difference",
                                   withinvars = "loadType",
                                   idvar = "subjectID")


```

## Plot the data

### Plot settings
```{r plot settings}

text.theme = theme(plot.title = element_text(size = 15, 
                                             hjust = 0.5, 
                                             lineheight = 1.2,
                                             family = "Helvetica Neue", 
                                             face = "bold"),
                   axis.title.x = element_text(size = 14,
                                               family = "Helvetica Neue",
                                               face = "bold"),
                   axis.title.y = element_text(size = 14,
                                               family = "Helvetica Neue",
                                               face = "bold"),
                   axis.text.x = element_text(size = 12,
                                              family = "Helvetica Neue"),
                   axis.text.y = element_text(size = 12,
                                              family = "Helvetica Neue"))


legend.theme = theme(legend.position = "bottom",
                     legend.title = element_text(size = 11,
                                                 family = "Helvetica Neue",
                                                 face = "bold"))

legend.none = theme(legend.position = "none")

color_1 = "#C7A0C7" 
color_2 = "#E6C9E6" 
color_3 = "#1CB4A5"
color_4 = "#96D6CE"

color_5 = "#FDBD70"
color_6 = "#8CCAE9"

```

### Decision times
```{r plot DT}

ggplot(summary.rt.subj.load, 
       aes(x = loadType, y = responseTimeClean, col = loadType, fill = loadType, group = loadType)) +
  
  geom_rain(id.long.var = 'subjectID', rain.side = "f1x1",
            line.args = rlang::list2(alpha = 1, color = "grey"),
            point.args = rlang::list2(color = "grey", size = 1),
            violin.args = list(alpha = 1, size = 1, linewidth = 0.75),
            boxplot.args = list(alpha = 1, color = 'black', linewidth = 0.75))+
 
  scale_colour_manual(values = c(color_1, color_3)) +
  scale_fill_manual(values = c(color_1, color_3)) +

  scale_y_continuous("Decision time (ms)") +
  scale_x_discrete("Memory load") +

  coord_cartesian(ylim = c(400,1800)) +

  theme_bw() +
  text.theme +
  legend.none


```


```{r plot DT with dial}
ggplot(summary.rt.load.dial, 
       aes(x = loadType, y = responseTimeClean, col = loadType, fill = loadType, group = loadType)) +
  
  geom_bar(stat = "identity", position = position_dodge(width = 1), 
           color = "black", width = 0.5, size = 0.4) +
  
  geom_line(data = summary.rt.subj.load.dial, aes(group = subjectID), color= "grey", size = 0.4) +

  geom_errorbar(aes(ymin = responseTimeClean-se, ymax = responseTimeClean+se), width = 0.1, 
                position = position_dodge(0.9), size = 0.5, color = "black") +  
  
  scale_fill_manual(values = c(color_1, color_3)) +
  
  facet_grid(~dialType, scales = 'free_x')+
  scale_y_continuous("Decision time (s)") +
  scale_x_discrete("Memory load") +

  coord_cartesian(ylim = c(100,1800)) +

  theme_classic() +
  text.theme +
  legend.none

```

### Error

```{r plot err}

ggplot(summary.err.subj.load, 
       aes(x = loadType, y = difference, col = loadType, fill = loadType, group = loadType)) +
  
  geom_rain(id.long.var = 'subjectID', rain.side = "f1x1",
            line.args = rlang::list2(alpha = 1, color = "grey"),
            point.args = rlang::list2(color = "grey", size = 1),
            violin.args = list(alpha = 1, size = 1, linewidth = 0.75),
            boxplot.args = list(alpha = 1, color = 'black', linewidth = 0.75))+
 
  scale_colour_manual(values = c(color_1, color_3)) +
  scale_fill_manual(values = c(color_1, color_3)) +

  scale_y_continuous("Absolute error (degrees)") +
  scale_x_discrete("Memory load") +

  coord_cartesian(ylim = c(5,40)) +

  theme_bw() +
  text.theme +
  legend.none

```

```{r plot err with dial}
ggplot(summary.err.load.dial, 
       aes(x = loadType, y = difference, col = loadType, fill = loadType, group = loadType)) +
  
  geom_bar(stat = "identity", position = position_dodge(width = 1), 
           color = "black", width = 0.5, size = 0.4) +
  
  geom_line(data = summary.err.subj.load.dial, aes(group = subjectID), color= "grey", size = 0.4) +

  geom_errorbar(aes(ymin = difference-se, ymax = difference+se), width = 0.1, 
                position = position_dodge(0.9), size = 0.5, color = "black") +  
  
  scale_fill_manual(values = c(color_1, color_3)) +
  
  facet_grid(~dialType, scales = 'free_x')+
  scale_y_continuous("Absolute error (degrees)") +
  scale_x_discrete("Memory load") +

  coord_cartesian(ylim = c(5,40)) +

  theme_classic() +
  text.theme +
  legend.none

```


```{r plot err bars}

ggplot(summary.err.load.dial, 
       aes(x = dialType, y = difference, 
           col = interaction(loadType, dialType), 
           fill = interaction(loadType, dialType), 
           group = dialType)) +
  
  geom_bar(stat = "identity", position = position_dodge(width = 1), 
           color = "black", width = 0.5, size = 0.4) +
  
  geom_errorbar(aes(ymin = difference-se, ymax = difference+se), width = 0.1, 
                position = position_dodge(0.9), size = 0.5, color = "black") +  
  
  scale_fill_manual(values = c(color_1, color_3, color_2, color_4)) +
  
  facet_grid(~loadType, scales = 'free_x')+
  scale_y_continuous("Absolute error (degrees)") +
  scale_x_discrete("Memory load") +

  coord_cartesian(ylim = c(5,30)) +

  theme_classic() +
  text.theme +
  legend.none

```

```{r plot rt bars}

ggplot(summary.rt.load.dial, 
       aes(x = dialType, y = responseTimeClean, 
           col = interaction(loadType, dialType), 
           fill = interaction(loadType, dialType), 
           group = dialType)) +
  
  geom_bar(stat = "identity", position = position_dodge(width = 1), 
           color = "black", width = 0.5, size = 0.4) +
  
  geom_errorbar(aes(ymin = responseTimeClean-se, ymax = responseTimeClean+se), width = 0.1, 
                position = position_dodge(0.9), size = 0.5, color = "black") +  
  
  scale_fill_manual(values = c(color_1, color_3, color_2, color_4)) +
  
  facet_grid(~loadType, scales = 'free_x')+
  scale_y_continuous("Decision time (s)") +
  scale_x_discrete("Response dial") +

  coord_cartesian(ylim = c(100,1500)) +

  theme_classic() +
  text.theme +
  legend.none

```
### Rain main effects

``` {r main effects rt}

rt.sub.load = data %>% 
  group_by(subjectID, loadType) %>% 
  summarise(loadRT = mean(responseTimeClean, na.rm = TRUE)) %>% 
  pivot_wider(names_from = loadType, values_from = loadRT) %>% 
  transmute(Effect = Four - Two)

rt.sub.dial = data %>% 
  group_by(subjectID, dialType) %>% 
  summarise(dialRT=mean(responseTimeClean, na.rm=TRUE)) %>% 
  pivot_wider(names_from=dialType,values_from=dialRT) %>% 
  transmute(Effect = Right - Up)

rt.effects = bind_rows(
  list(Load = rt.sub.load, Dial = rt.sub.dial),
  .id = 'effectType')

rt.effects$effectType = factor(rt.effects$effectType, levels=c("Load", "Dial"))
rt.effects$effectType = factor(rt.effects$effectType, levels = rev(levels(rt.effects$effectType)))
```

``` {r main effects err}
err.sub.load = data %>% 
  group_by(subjectID, loadType) %>% 
  summarise(loadRT = mean(difference, na.rm = TRUE)) %>% 
  pivot_wider(names_from = loadType, values_from = loadRT) %>% 
  transmute(Effect = Four - Two)

err.sub.dial = data %>% 
  group_by(subjectID, dialType) %>% 
  summarise(dialRT=mean(difference, na.rm=TRUE)) %>% 
  pivot_wider(names_from=dialType,values_from=dialRT) %>% 
  transmute(Effect = Right - Up)

err.effects = bind_rows(
  list(Load = err.sub.load, Dial = err.sub.dial),
  .id = 'effectType')

err.effects$effectType = factor(err.effects$effectType, levels=c("Load", "Dial"))
err.effects$effectType <- factor(err.effects$effectType, levels = rev(levels(err.effects$effectType)))

```


``` {r rain effects rt}

ggplot(rt.effects, aes(x = effectType, y = Effect, fill = effectType)) +
  
  geom_violin(alpha = 1, size = 0.75, width = 0.8, trim = FALSE) +
  geom_boxplot(alpha = 1, width = 0.1, outlier.shape = NA) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray40") +
  
  scale_fill_manual(values = c(color_6, color_5)) +
  scale_y_continuous("Decision time difference (s)") +
  scale_x_discrete("Main effects") +

  theme_classic() +
  text.theme +
  legend.none + 
  coord_flip()

```

``` {r rain effects rt}

ggplot(err.effects, aes(x = effectType, y = Effect, fill = effectType)) +
  
  geom_violin(alpha = 1, size = 0.75, width = 0.8, trim = FALSE) +
  geom_boxplot(alpha = 1, width = 0.1, outlier.shape = NA) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray40") +
  
  scale_fill_manual(values = c(color_6, color_5)) +
  scale_y_continuous("Error difference (deg)") +
  scale_x_discrete("Main effects") +

  theme_classic() +
  text.theme +
  legend.none + 
  coord_flip()

```

### Stats

```{r stats}

### Absolute error
anov_Err <- aov(difference ~ loadType * dialType, data = summary.err.subj.load.dial)
summary(anov_Err)

### Decision time
anov_RT <- aov(responseTimeClean ~ loadType * dialType, data = summary.rt.subj.load.dial)
summary(anov_RT)

aov_ez(
    id = 'subjectID',
    within = c('dialType', 'loadType'),
    dv = 'difference',
    data = summary.err.subj.load.dial)

aov_ez(
    id = 'subjectID',
    within = c('dialType', 'loadType'),
    dv = 'responseTimeClean',
    data = summary.rt.subj.load.dial)


```

